# Manify Benchmarking Configuration

# Weights & Biases configuration
wandb:
  project: mixed-curvature
  entity: chlenski  # Set to your wandb username or team
  name: manify-benchmark-run

# Common settings for all benchmark types
common:
  # Task settings
  classification_metrics:
    - accuracy
    - f1-micro
  regression_metrics:
    - rmse
    - mse
  
  # Model selection - applies to all benchmarks unless overridden
  models:
    - sklearn_dt
    - sklearn_rf
    - product_dt
    - product_rf
    - tangent_dt
    - tangent_rf
    - knn
    - ps_perceptron
    - ambient_mlp
    - ambient_gnn
    - kappa_gcn
    - product_mlr
  
  # Device settings
  device: cuda           # Device to use (cuda, mps, cpu)
  
  # Output settings
  output_dir: data/results_wandb
  
  # Default number of trials
  n_trials: 1
  
  # Points per dataset (common for all data types)
  n_points: 1000

# Gaussian mixture model specific settings (applies to both single and signature)
gaussian:
  # Gaussian generation settings
  n_trials_gaussian: 1  # Specific number of trials for Gaussian benchmarks
  n_classes: 8
  n_clusters: 32
  cov_scale_means: 1.0
  cov_scale_points: 1.0

# Single curvature Gaussian benchmark settings
single_curvature:
  # Minimal curvature set for testing
  curvatures: [0]
  dimension: 2
  n_classes: 2      # Reduce complexity
  n_clusters: 4     # Reduce complexity
  n_points: 100     # Reduce dataset size
  # Run both classification and regression tasks

# Signature Gaussian benchmark settings (mixed curvature)
signature_gaussian:
  signatures:
    - [[-1, 2], [0, 2]]   # HE
    - [[-1, 2], [1, 2]]   # HS  
    - [[0, 2], [1, 2]]    # ES
    - [[-1, 2], [-1, 2]]  # HH
    - [[1, 2], [1, 2]]    # SS
  signature_names:
    - HE
    - HS
    - ES
    - HH
    - SS
  # Run both classification and regression tasks

# Graph Embedding benchmark settings
graph_embedding:
  embeddings_dir: data/graphs/embeddings
  data_dir: data/graphs
  embedding_names:
    - polblogs
    - cora
    - citeseer
    - cs_phds
  signatures:
    - SS
    - H
    - HS
  # Task-specific overrides
  task_overrides:
    cs_phds: regression  # Override task for this dataset
    polblogs: classification
    cora: classification
    citeseer: classification

# VAE Embedding benchmark settings
vae_embedding:
  data_dir: data
  embedding_names:
    - blood_cell_scrna
    - lymphoma
    - cifar_100
    - mnist
  signatures:
    - [[1, 2], [0, 2], [-1, 2], [-1, 2], [-1, 2]]  # blood_cell_scrna
    - [[1, 2], [1, 2]]                             # lymphoma
    - [[1, 2], [1, 2], [1, 2], [1, 2]]             # cifar_100
    - [[1, 2], [0, 2], [-1, 2]]                    # mnist
  n_samples: 1000  # Subsample large datasets to this size
  # All VAE embeddings use classification