# Manify Benchmarking Configuration

# Weights & Biases configuration
wandb:
  project: mixed-curvature
  entity: chlenski
  name: manify-benchmark-run

# Common settings for all benchmark types
common:
  # Core parameters used across all benchmarks
  n_trials: 1             # Number of trials/seeds to run per benchmark
  n_points: 1000           # Number of points to use (for data generation or subsampling)
  
  # Task settings
  classification_metrics: [accuracy, f1-micro]
  regression_metrics: [rmse, mse]
  
  # Model selection - applies to all benchmarks unless overridden
  models:
    - sklearn_dt
    # - sklearn_rf
    # - product_dt
    # - product_rf
    # - tangent_dt
    # - tangent_rf
    # - knn
    # - ps_perceptron
    # - ambient_mlp
    # - ambient_gnn
    # - kappa_gcn
    # - product_mlr
  
  # Device settings
  device: cuda           # Device to use (cuda, mps, cpu)
  
  # Output settings
  output_dir: data/results_wandb
  
  # Tree parameters
  max_depth: 5           # Tree max depth (used in multiple benchmark types)

# Gaussian mixture model common settings
gaussian:
  # Gaussian generation settings
  n_classes: 8
  n_clusters: 32
  cov_scale_means: 1.0
  cov_scale_points: 1.0

# Single curvature Gaussian benchmark settings
single_curvature:
  # Minimal curvature set for testing
  curvatures: [-4, -2, -1, 0, 1, 2, 4]
  dimension: 2
  # Uses n_trials from common section
  # Run both classification and regression tasks

# Signature Gaussian benchmark settings (mixed curvature)
signature_gaussian:
  signatures:
    - [[-1, 2], [0, 2]]   # HE
    - [[-1, 2], [1, 2]]   # HS  
    - [[0, 2], [1, 2]]    # ES
    - [[-1, 2], [-1, 2]]  # HH
    - [[1, 2], [1, 2]]    # SS
    - [[-1, 4]] # H
    - [[1, 4]] # S
    - [[0, 4]] # E
  signature_names: [HE, HS, ES, HH, SS, H, S, E]
  # Uses n_trials from common section
  # Run both classification and regression tasks

# Graph Embedding benchmark settings
graph_embedding:
  embeddings_dir: data/graphs/embeddings
  data_dir: data/graphs
  embedding_names: [polblogs, cora, citeseer, cs_phds]
  signatures: [SS, H, HS, H]

  # Task-specific overrides
  task_overrides:
    cs_phds: regression
    polblogs: classification
    cora: classification
    citeseer: classification
  # Uses n_trials from common section

# VAE Embedding benchmark settings
vae_embedding:
  data_dir: data
  embedding_names: [blood_cell_scrna, lymphoma, cifar_100, mnist]
  signatures:
    - [[1, 2], [0, 2], [-1, 2], [-1, 2], [-1, 2]]  # blood_cell_scrna
    - [[1, 2], [1, 2]]                             # lymphoma
    - [[1, 2], [1, 2], [1, 2], [1, 2]]             # cifar_100
    - [[1, 2], [0, 2], [-1, 2]]                    # mnist
  # Uses n_points from common for subsampling large datasets
  # All VAE embeddings use classification
  task: classification
  # Uses n_trials from common section

# Link Prediction benchmark settings
link_prediction:
  data_dir: data/graphs
  graph_names: [karate_club, lesmis, dolphins, polbooks, adjnoun, football]
  component_signatures:
    - [[-1, 2], [0, 2], [1, 2]]  # HES - Hyperbolic, Euclidean, Spherical
  component_names:
    - HES
  # Training parameters
  embedding_iterations: 5000
  test_size: 0.2
  add_dists: true
  learning_rate: 0.0001

# Empirical Datasets benchmark settings
empirical_benchmarks:
  dataset_names: [landmasses, neuron_33, neuron_46, temperature, traffic]
  signatures:
    - [[1, 2]]                   # landmasses
    - [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]  # neuron_33
    - [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]  # neuron_46
    - [[1, 2], [1, 1]]          # temperature
    - [[0, 1], [1, 1], [1, 1], [1, 1], [1, 1]]  # traffic
  tasks: [classification, classification, classification, regression, regression]
  # Uses n_points from common section for subsampling large datasets
  # Uses n_trials from common section