site_name: Manify
theme: readthedocs

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ["manify"]  
          options:
            docstring_style: google
            merge_init_into_class: true
            show_root_heading: true
            show_source: true
            show_category_heading: false
            members_order: source
            show_submodules: true
            filters: ["!^_", "!^Parameters$"]
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py

# Explicitly define navigation structure
nav:
  - Home: index.md
  - API Reference:
    - Overview: reference/index.md
    - Manifolds: reference/manifolds.md
    - Curvature Estimation: 
      - Overview: reference/curvature_estimation/index.md
      - Delta Hyperbolicity: reference/curvature_estimation/delta_hyperbolicity.md
      - Greedy Method: reference/curvature_estimation/greedy_method.md
      - Sectional Curvature: reference/curvature_estimation/sectional_curvature.md
    - Embedders:
      - Overview: reference/embedders/index.md
      - Coordinate Learning: reference/embedders/coordinate_learning.md
      - Siamese: reference/embedders/siamese.md
      - VAE: reference/embedders/vae.md
    - Predictors:
      - Overview: reference/predictors/index.md
      - Decision Tree: reference/predictors/decision_tree.md
      - Kappa GCN: reference/predictors/kappa_gcn.md
      - Perceptron: reference/predictors/perceptron.md
      - SVM: reference/predictors/svm.md
    - Utils:
      - Overview: reference/utils/index.md
      - Benchmarks: reference/utils/benchmarks.md
      - Dataloaders: reference/utils/dataloaders.md
      - Link Prediction: reference/utils/link_prediction.md
      - Preprocessing: reference/utils/preprocessing.md
      - Visualization: reference/utils/visualization.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true