site_name: Manify
theme:
  name: material

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ["manify"]
          options:
            docstring_style: google
            merge_init_into_class: true

nav:
  - Home: index.md
  - API: api.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
