name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package & test deps
        run: pip install -e '.[test]'

      - name: Check formatting with Black
        run: black --check .

      - name: Check import sorting with isort
        run: isort --check --profile black .

      - name: Run Pytest with coverage
        run: pytest --cov=src --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

      - name: Install MyPy
        run: pip install mypy

      - name: Run MyPy type checks
        run: mypy src/ --ignore-missing-imports
        # adjust path (src/) or flags as needed


